### ISSUE TITLE
crash with cryo ducts

### ISSUE THREAD

**Issue by LeChuckXIV** [halvors/ElectricityMeter#57] opened 2015-10-10 18:14 UTC
getting a crash loop on a server, my setup has an induction port outputting into a cryo-stabilised duct, going into a tesseract.

crashlog: http://pastebin.com/1AL5NY0A

**Comment by halvors** [comment] 2015-10-10 20:26
Do you have a world that i can use to reproduce this issue?

**Comment by halvors** [comment] 2015-10-10 21:35
Duplicate of #56

**Closed as completed by halvors** 2015-10-10 21:35 UTC
Labels: bug
